import = ["/home/senyaa/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 10

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = -1

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
# family = "Comic Mono"
style = "Normal"

[shell]
program = "/bin/fish"

[window]
dynamic_padding = false
opacity = 0.5

[window.padding]
x = 10
y = 10
